-- Apply this script to the warehouse-management Supabase project only.
-- It is no longer intended for the main ordering database.

CREATE TABLE IF NOT EXISTS public.warehouse_receipts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_order_id integer NOT NULL,
    source_order_code character varying(100) NOT NULL,
    source_request_code character varying(100) NOT NULL,
    site_code character varying(100),
    site_name character varying(255),
    result_status character varying(50) NOT NULL,
    has_discrepancy boolean NOT NULL DEFAULT false,
    discrepancy_note text,
    overall_note text,
    confirmed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_by_account_id integer,
    confirmed_by_username character varying(100)
);

CREATE TABLE IF NOT EXISTS public.warehouse_receipt_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id integer NOT NULL REFERENCES public.warehouse_receipts(id) ON DELETE CASCADE,
    source_order_item_id integer,
    merchandise_code character varying(100),
    merchandise_name character varying(255),
    ordered_quantity numeric(10,2) NOT NULL,
    received_quantity numeric(10,2) NOT NULL,
    unit character varying(100),
    transport_method character varying(100),
    inspection_result character varying(50) NOT NULL,
    item_note text
);
